CREATE OR REPLACE PROCEDURE PROC_BLOG_INSERT 
(
  TITULO_B IN BLOG.TITULO_BLOG%TYPE, 
  DESCRICAO_B IN BLOG.DESCRICAO_BLOG%TYPE
) IS
BEGIN
  INSERT INTO BLOG (TITULO_BLOG, DESCRICAO_BLOG)	
  VALUES (TITULO_B, DESCRICAO_B);
END PROC_BLOG_INSERT;