create or replace 
PROCEDURE PROC_USUARIO_INSERT (
  p_nome IN USUARIO.NOME_USUARIO%TYPE, 
  p_login IN USUARIO.LOGIN_USUARIO%TYPE,
  p_senha IN USUARIO.SENHA_USUARIO%TYPE,
  p_bio IN USUARIO.BIO_USUARIO%TYPE
) 
  IS
  BEGIN
    INSERT INTO USUARIO (ID_USUARIO, NOME_USUARIO, LOGIN_USUARIO, SENHA_USUARIO, BIO_USUARIO) 
        VALUES  (SQUSUARIO.nextVal, p_nome, p_login, p_senha, p_bio);
    COMMIT;    
  END PROC_USUARIO_INSERT;