CREATE OR REPLACE PROCEDURE PROC_COMENTARIO_INSERT (
  p_datacriacao in COMENTARIO.DATACRIACAO_COMENTARIO%TYPE,
  p_conteudo in COMENTARIO.CONTEUDO_COMENTARIO%TYPE,
  p_nome in COMENTARIO.NOME_COMENTARIO%TYPE,
  p_email in COMENTARIO.EMAIL_COMENTARIO%TYPE,
  p_post_id in COMENTARIO.ID_POST%TYPE
) 
  IS
  BEGIN
    INSERT INTO COMENTARIO (ID_COMENTARIO, DATACRIACAO_COMENTARIO, CONTEUDO_COMENTARIO,
                            NOME_COMENTARIO, EMAIL_COMENTARIO, ID_POST)
            VALUES          (SQCOMENTARIO.nextVal, p_datacriacao, p_conteudo, p_nome,
                            p_email, p_post_id);    
    COMMIT;    
  END PROC_COMENTARIO_INSERT;