CREATE OR REPLACE PROCEDURE PROC_COMENTARIO_DELETE (
  p_id    IN COMENTARIO.ID_COMENTARIO%TYPE
  ) 
  IS
  BEGIN
    DELETE FROM COMENTARIO
    WHERE (COMENTARIO.ID_COMENTARIO = p_id);
    COMMIT;
  END PROC_COMENTARIO_DELETE;