CREATE OR REPLACE PROCEDURE PROC_USUARIO_DELETE (
  p_id    IN USUARIO.ID_USUARIO%TYPE
  ) 
  IS
  BEGIN
    DELETE FROM USUARIO
    WHERE (USUARIO.ID_USUARIO = p_id);
    COMMIT;    
  END PROC_USUARIO_DELETE;