CREATE OR REPLACE SEQUENCE SQ_BLOG
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
  
CREATE OR REPLACE TRIGGER TRG_SQ_BLOG
  BEFORE INSERT ON BLOG
  FOR EACH ROW
BEGIN
  :new.ID_BLOG := SQ_BLOG.nextval;
END;