CREATE OR REPLACE PROCEDURE PROC_BLOG_INSERT (
  p_titulo IN BLOG.TITULO_BLOG%TYPE, 
  p_descricao IN BLOG.DESCRICAO_BLOG%TYPE 
) 
  IS
  BEGIN
    INSERT INTO BLOG (ID_BLOG, TITULO_BLOG, DESCRICAO_BLOG) 
        VALUES  (SQBLOG.nextVal, p_titulo, p_descricao);
    COMMIT;    
  END PROC_BLOG_INSERT;